### ISSUE TITLE
Invalid JSON generated when addtional information is added to access token

### ISSUE THREAD

**Issue by domurtag** [bluesliverx/grails-spring-security-oauth2-provider#87]
I've been trying to add additional information to the JSON object that is returned when the authentication code is exchanged for an access token. 

## Attempt No. 1

My first attempt at achieving this was to replace the `tokenService` bean defined by the plugin with one that returns an access token with a non-empty `additionalInformation` map, i.e.

````groovy
class MyTokenStoreService extends GormTokenStoreService {

    @Override
    OAuth2AccessToken getAccessToken(OAuth2Authentication authentication) {
        OAuth2AccessToken token = super.getAccessToken(authentication)

        if (token) {
            (token as DefaultOAuth2AccessToken).setAdditionalInformation([foo: 'bar'])
            log.debug "Added additional info to token: $token.additionalInformation"
        }

        return token
    }
}
````
The code in the OAuth client that exchanges the auth code for an access code is shown below

````groovy
def exchangeAuthCode(String authCode) {

    def callback = grailsLinkGenerator.link(controller: 'auth', action: 'callback', absolute: true)

    def params = [
            // the scope param is not required by the OAuth spec. it's a workaround for this issue
            // https://github.com/bluesliverx/grails-spring-security-oauth2-provider/issues/64
            scope: 'read',
            grant_type: 'authorization_code',
            code: authCode,
            client_id: 'my-client',
            redirect_uri: callback
    ]

    def oauthProviderAccessTokenUrl = "$oauthProvider/oauth/token"

    new HTTPBuilder(oauthProviderAccessTokenUrl).request(POST, JSON) {
        uri.query = params

        response.success = { resp, json ->
            json
        }

        response.failure = { resp, json ->
            log.error "HTTP error code: $resp.status, status line: $resp.statusLine, "

            json.each { key, value ->
                log.error "$key: $value"
            }
        }
    }
}
````
When the response to the HTTP POST is received, the following error occurs

> groovy.json.JsonException: expecting '}' or ',' but got current char '' with an int value of 0
> The current character read is '' with an int value of 0
> expecting '}' or ',' but got current char '' with an int value of 0
> line number 1
> index number 255
> {"access_token":"f9f0cd8d-0a5d-43a5-bda0-d08c58b8cff5","token_type":"bearer","refresh_token":"df779a97-7aed-490e-b1ef-0fd4f7be6a7e","expires_in":43160,"scope":"read","foo":"bar"

Notice that the closing JSON character `}` is absent. 

If instead I use the default `tokenService` bean provided by the plugin - which does not populate `additionalInformation` - this problem does not occur

## Attempt No. 2

I also tried to use a `TokenEnhancer` to populate the access token's `additionalInformation` map
````groovy
class CustomTokenEnhancer implements TokenEnhancer {
    @Override
    OAuth2AccessToken enhance(OAuth2AccessToken accessToken, OAuth2Authentication authentication) {

        if (accessToken) {

            DefaultOAuth2AccessToken defaultAccessToken = accessToken as DefaultOAuth2AccessToken
            defaultAccessToken.setAdditionalInformation([foo: 'bar'])
            accessToken = defaultAccessToken
            log.info "Additional token info: $accessToken.additionalInformation"
        }

        accessToken
    }
}
````

I registered this as a Spring bean in `resources.groovy` and set it as a dependency of the `tokenServices` bean
````groovy
tokenEnhancer(CustomTokenEnhancer)
    
tokenServices(DefaultTokenServices) {
    tokenEnhancer = ref("tokenEnhancer")

    // These are the same as the dependencies defined by the plugin in SpringSecurityOauth2ProviderGrailsPlugin.groovy
    tokenStore = ref("tokenStore")
    clientDetailsService = ref("clientDetailsService")
    accessTokenValiditySeconds = conf.oauthProvider.tokenServices.accessTokenValiditySeconds
    refreshTokenValiditySeconds = conf.oauthProvider.tokenServices.refreshTokenValiditySeconds
    reuseRefreshToken = conf.oauthProvider.tokenServices.reuseRefreshToken
    supportRefreshToken = conf.oauthProvider.tokenServices.supportRefreshToken
}
````    
However, I get exactly the same error in this case, i.e. it appears that the JSON response is missing a closing "}".

**Comment by donalmurtagh** [comment]
If you need it, I could probably make available a pair of apps - one for the OAuth provider and one for the client - that demonstrates this issue

**Comment by donalmurtagh** [comment]
The commit referenced above demonstrates how I'm working around this issue, i.e. by parsing the response as text with the Apache HttpClient lib and converting it to JSON myself. Previously I was parsing it as JSON with the Groovy HttpBuilder lib. The latter works only when there's no additional information added to the access token response.

**Comment by dynamind** [comment]
After some attempts, I'm starting to think that using a TokenEnhancer is the only correct way. I did not run into any corrupt JSON issues, just that `additionalInformation` **can not be set via a `TokenStore` if there's no existing access token**. The reason is this method in `DefaultTokenServices.java`:

    public OAuth2AccessToken createAccessToken(OAuth2Authentication authentication) throws AuthenticationException {
        OAuth2AccessToken existingAccessToken = tokenStore.getAccessToken(authentication);
        if (existingAccessToken != null) {
            ...
            return existingAccessToken; // Provided by our TokenStore implementation
        }
        ...
        OAuth2AccessToken accessToken = createAccessToken(authentication, refreshToken);
        ...
        return accessToken;
    }

Which calls the private method:

    private OAuth2AccessToken createAccessToken(OAuth2Authentication authentication, OAuth2RefreshToken refreshToken) {
        DefaultOAuth2AccessToken token = new DefaultOAuth2AccessToken(UUID.randomUUID().toString());
        int validitySeconds = getAccessTokenValiditySeconds(authentication.getOAuth2Request());
        if (validitySeconds > 0) {
            token.setExpiration(new Date(System.currentTimeMillis() + (validitySeconds * 1000L)));
        }
        token.setRefreshToken(refreshToken);
        token.setScope(authentication.getOAuth2Request().getScope());

        return accessTokenEnhancer != null ? accessTokenEnhancer.enhance(token, authentication) : token;
    }

As you see in the last line, the only way to augment this token is via a provided TokenEnhancer.

That said, when I do manage to set `additionalInformation`, it is added to the JSON as expected:

    >curl -u web-client: -d grant_type=client_credentials -d scope=read http://localhost:8080/api/oauth/token
    {"access_token":"1f996e44-a846-42e5-a74f-4e78124ec246","token_type":"bearer","expires_in":43194,"scope":"read","foo":"bar"}

Which version of the plugin are you using?

**Comment by domurtag** [comment]
I'm using the most recent version of the plugin 2.0-SNAPSHOT. I'm currently trying to add the additional information with a `tokenEnhancer` that is set as a property of the `tokenServices` bean as shown in "Attempt No. 2" above.

You can see the problem in action if you download this [OAuth provider app](https://github.com/domurtag/oauth2-provider) and this [OAuth Client app](https://github.com/domurtag/oauth-client) then follow the instructions below

 - Start the OAuth provider app with `grails run-app`
 - Start the OAuth client on port 9090 with `grails run-app -Dserver.port=9090`
 - On the homepage of the client app click the "OAuth Login" link. This redirects to the provider app and prompts you to login. 
 - Enter the username "me", password "password", and click the "Authorize" button in the confirmation dialog that follows. The access token response is displayed in the browser

By default everything looks fine, you can see that all the expected fields - including the username which is added by the token enhancer - are returned. However there are a couple of issues

## Problem 1 - Request Another Token
If you click the "OAuth Login" button again, this time the additional information is not returned, but all the other fields are

## Problem 2 - Parse Response as JSON
This is the issue I originally mentioned. You'll notice that the client includes [a switch](https://github.com/domurtag/oauth-client/blob/master/grails-app/services/org/example/OauthService.groovy#L24) which controls whether the access token response is parsed as JSON by HttpBuilder or parsed as text by HttpClient. If you flip the switch so that HttpBuilder is used instead, you'll see the issue I originally mentioned. While is tempting to put this down to a bug in HttpBuilder, I don't think it's quite this simple, because if you remove the token enhancer, the response *can* be parsed with HttpBuilder.

**Comment by bobby-vandiver** [comment]
I pushed a [commit](https://github.com/bluesliverx/grails-spring-security-oauth2-provider/commit/cf511223d4a811b87fc06282bd0dbdef374a5758) just now to provide basic support for registering one or more instances of `TokenEnhancer` via `TokenEnhancerChain`.

You'll need to register each `TokenEnhancer` as a bean in `resources.groovy` and then specify the list of bean names in the `grails.plugin.springsecurity.oauthProvider.tokenServices.tokenEnhancerBeanNames` property in `Config.groovy`. You can check out the above commit for more details.

This is very much a WIP, so feedback is more than welcome.

@domurtag Please grab the latest SNAPSHOT build when it finishes building and see if that resolves your issue. I have not had a chance to pull your projects and confirm myself yet, but I will tomorrow evening.

**Comment by domurtag** [comment]
Thanks for adding the `TokenEnhancerChain` support. I've updated the provider app to use this, so you can revert the local changes you've made to `Config.groovy` and `resources.groovy` and just pull the latest from GitHub.

However, after making these changes, I'm still unable to parse with `HttpBuilder`. I guess either I'm missing something, or perhaps you thought you were using `HttpBuilder` but were really using `HttpClient` e.g. you flipped the `parseWithHttpBuilder` switch, but didn't restart the app (automatic code reloading is a bit hit-and-miss in my experience).

Anyway, could you pull the changes and see if your experience is the same as mine or let me know if I've missed something? Thanks again.

**Comment by domurtag** [comment]
I realise the `TokenEnhancerChain` support is a WIP, but instead of requiring the user to configure the token enhancer beans in `Config.groovy`, e.g.

    grails.plugin.springsecurity.oauthProvider.tokenServices.tokenEnhancerBeanNames = ['usernameTokenEnhancer']

you could instead automatically detect them in `doWithApplicationContext` in the plugin descriptor

    def doWithApplicationContext = { appCtx ->
        // iterate through the beans and find those that are an instanceof TokenEnhancer
    }

**Comment by bobby-vandiver** [comment]
@domurtag I got a capture of the network traffic using Wireshark and confirmed that the JSON returned by the server is well-formed and valid. I am seeing the same error you reported earlier, though.

I did a little digging and found [this SO post](http://stackoverflow.com/questions/25704985/groovy-httpbuilder-producing-error-when-parsing-valid-json). It looks like the error is due to Groovy 2.3 and later, which is what Grails 2.4.x uses. So, this is a legit issue with HTTPBuilder and not a plugin issue.

**Comment by domurtag** [comment]
@bobby-vandiver thanks a lot for your investigation. Do you have any idea why the additional information is only returned the first time an access token is retrieved, i.e. "Problem 1" above?

**Comment by dynamind** [comment]
When I used the non-TokenEnhancer method, it was the other way around; the first time I didn't get additional information, but the second time it did because it was provided by my `GormTokenStoreService`. 
If you don't want to persist the additional information, you could override `readAccessToken()` and `getAccessToken()` (and probably a few more). Ideally you would add it to `createOAuth2AccessToken()` to catch them all, but that is a private method. I got around this by creating my own `GormTokenStoreService` in stead of extending the one provided by the plugin.

**Comment by bobby-vandiver** [comment]
I pushed a [commit](https://github.com/bluesliverx/grails-spring-security-oauth2-provider/commit/ed51696795cbd246f7a7cd6b28d6c1d0098c1a81) just now to add support for persisting additional information.

**Comment by domurtag** [comment]
Thanks @bobby-vandiver, will this fix the issue I referred to as "Problem 1", i.e.

> If you click the "OAuth Login" button again, this time the additional information is not returned, but all the other fields are

Are your changes available in the latest `2.0-SNAPSHOT` release? If so, I'll try them out when I'm back at work on Tuesday (it's a public holiday here tomorrow).

**Comment by bobby-vandiver** [comment]
@domurtag Yeah, this will fix "Problem 1". The latest `2.0-SNAPSHOT` has this change. I'll leave this issue open until you can confirm that the latest plugin resolves your issue.

**Comment by domurtag** [comment]
Thanks again, I'll test it out on Tuesday, and provide feedback here

**Comment by donalmurtagh** [comment]
I [updated my example provider app](https://github.com/domurtag/oauth2-provider/commit/36c6dfec0611224915286346582328386a0eb526) to incorporate the latest changes and it works like a charm, i.e. "Problem 1" is resolved. Thanks a lot!
